# Generated by Django 3.1.5 on 2021-11-19 10:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="alarm_details",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manual_name", models.CharField(max_length=20)),
                ("manual_number", models.CharField(max_length=20)),
                ("alarm_details", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("special_tips", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="product_type",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="userdetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("company_name", models.CharField(max_length=50)),
                ("company_add", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=20)),
                ("pincode", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("designation", models.CharField(max_length=30)),
                ("mobilenumber", models.PositiveIntegerField()),
                ("flag_1", models.BooleanField(default=False)),
                ("flag_2", models.BooleanField(default=False)),
                ("flag_3", models.BooleanField(default=False)),
                ("flag_4", models.BooleanField(default=False)),
                ("flag_5", models.BooleanField(default=False)),
                ("user_name", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="system_types",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_names", models.CharField(max_length=15)),
                (
                    "product_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_details",
                        to="servicesupport.product_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="alarms",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alarm", models.CharField(max_length=100)),
                (
                    "system_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system",
                        to="servicesupport.system_types",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="alarm_report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("report", models.CharField(max_length=200)),
                ("report_flag", models.BooleanField(default=False)),
                (
                    "alarm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_info",
                        to="servicesupport.alarm_details",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alarm_details",
            name="alarm_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_name",
                to="servicesupport.alarms",
            ),
        ),
        migrations.CreateModel(
            name="alarm_comments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("support", models.IntegerField()),
                ("machine", models.CharField(max_length=1000)),
                ("comment", models.TextField()),
                (
                    "alarm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_comment",
                        to="servicesupport.alarms",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
