# Generated by Django 3.1.5 on 2021-12-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="specification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parentspec", models.CharField(max_length=30)),
                ("childspec", models.CharField(max_length=30)),
                ("childname", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="product_type",
            name="product",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="system_types",
            name="system_names",
            field=models.CharField(max_length=20),
        ),
    ]
