# Generated by Django 3.1.5 on 2021-12-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0002_auto_20211211_1241"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="parentname",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="specification",
            name="parentspec",
            field=models.CharField(max_length=50),
        ),
    ]
