# Generated by Django 3.1.5 on 2021-12-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0003_auto_20211211_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="qty",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
