# Generated by Django 3.1.5 on 2021-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0004_specification_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarms",
            name="alarmname",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
