# Generated by Django 3.1.5 on 2021-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0005_alarms_alarmname"),
    ]

    operations = [
        migrations.CreateModel(
            name="equ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spec", models.CharField(max_length=50)),
                ("discription", models.CharField(max_length=70)),
                ("info", models.CharField(max_length=100)),
                ("equspec", models.CharField(max_length=100)),
                ("srno", models.CharField(max_length=50)),
                ("trno", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=150)),
            ],
        ),
    ]
