# Generated by Django 3.1.5 on 2021-12-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0006_equ"),
    ]

    operations = [
        migrations.AddField(
            model_name="equ",
            name="reuse",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equ",
            name="discription",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="equ",
            name="equspec",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equ",
            name="info",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equ",
            name="remark",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="equ",
            name="spec",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="equ",
            name="srno",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="equ",
            name="trno",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
