# Generated by Django 3.1.5 on 2021-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0007_auto_20211212_2304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equ",
            name="spec",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
