# Generated by Django 3.1.5 on 2021-12-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0008_auto_20211212_2329"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarms",
            name="alarmtag",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
