# Generated by Django 3.1.5 on 2021-12-19 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servicesupport", "0010_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="requesttype",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.CharField(max_length=30)),
                ("requestadd", models.CharField(max_length=30)),
                ("shortdetail", models.CharField(max_length=50)),
                ("details", models.CharField(max_length=200)),
                ("flag", models.BooleanField(default=False)),
                ("date", models.DateTimeField()),
                ("closedate", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="request",
        ),
    ]
