# Generated by Django 4.1.4 on 2023-02-02 11:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0011_auto_20211219_2059"),
    ]

    operations = [
        migrations.CreateModel(
            name="std",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Std_name", models.CharField(max_length=150)),
                ("MTB_name", models.CharField(max_length=100)),
                ("Machine_model", models.CharField(max_length=100)),
                (
                    "problem_solved",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                ("special_comments", models.CharField(max_length=150)),
                (
                    "Product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicesupport.product_type",
                    ),
                ),
                (
                    "System_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicesupport.system_types",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="std_partused",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Part_used", models.CharField(max_length=30)),
                ("Part_name", models.CharField(max_length=50)),
                ("file", models.FileField(blank=True, null=True, upload_to="Files")),
                (
                    "Std_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicesupport.std",
                    ),
                ),
            ],
        ),
    ]
