# Generated by Django 4.1.4 on 2023-03-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0012_std_std_partused"),
    ]

    operations = [
        migrations.AddField(
            model_name="system_types",
            name="nick_names",
            field=models.CharField(default="None", max_length=10),
        ),
    ]
