# Generated by Django 4.1.4 on 2023-03-13 06:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0013_system_types_nick_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarms",
            name="system_type",
        ),
        migrations.CreateModel(
            name="alarm_detail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alarm_number", models.CharField(max_length=20)),
                ("alarm_description", models.TextField(max_length=100)),
                (
                    "manual_name_number",
                    models.TextField(blank=True, default="not found", null=True),
                ),
                ("alarm_data", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("special_tips", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "system_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_name",
                        to="servicesupport.system_types",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="alarm_comments",
            name="alarm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_comment",
                to="servicesupport.alarm_detail",
            ),
        ),
        migrations.AlterField(
            model_name="alarm_report",
            name="alarm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_info",
                to="servicesupport.alarm_detail",
            ),
        ),
        migrations.DeleteModel(
            name="alarm_details",
        ),
        migrations.DeleteModel(
            name="alarms",
        ),
    ]
