# Generated by Django 4.1.4 on 2023-03-16 05:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servicesupport", "0014_remove_alarms_system_type_alarm_detail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="alarm_led",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Product_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Product_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("led_hexa", models.CharField(blank=True, max_length=5, null=True)),
                ("led_bits", models.CharField(blank=True, max_length=5, null=True)),
                ("led_text", models.CharField(blank=True, max_length=5, null=True)),
                ("led_description", models.TextField(max_length=100)),
                ("led_tips", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "led_manual",
                    models.TextField(blank=True, default="Not Available", null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="alarm_comments",
            name="machine",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="alarm_detail",
            name="system_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Alarm_system",
                to="servicesupport.system_types",
            ),
        ),
        migrations.AlterField(
            model_name="alarm_report",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="manual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Manual_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Manual_Name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Manual_storage", models.FileField(upload_to="uploads/")),
                ("comments", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Product_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_system",
                        to="servicesupport.system_types",
                    ),
                ),
            ],
        ),
    ]
