# Generated by Django 4.1.4 on 2023-03-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0015_alarm_led_alter_alarm_comments_machine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manual",
            name="Manual_storage",
            field=models.FileField(upload_to="uploads/manual/"),
        ),
        migrations.AlterField(
            model_name="specification",
            name="childname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="specification",
            name="childspec",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="specification",
            name="parentname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
