# Generated by Django 4.1.4 on 2023-03-23 07:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0016_alter_manual_manual_storage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm_comments",
            name="comment",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="alarm_comments",
            name="support",
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name="alarm_detail",
            name="alarm_data",
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="alarm_detail",
            name="manual_name_number",
            field=models.TextField(
                blank=True, default="not found", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alarm_detail",
            name="special_tips",
            field=ckeditor.fields.RichTextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="alarm_led",
            name="led_manual",
            field=models.TextField(
                blank=True, default="Not Available", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="childspec",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Training_model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Training_Name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Training_details",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("Manual_storage", models.FileField(upload_to="uploads/training/")),
                ("comments", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Product_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Training_product",
                        to="servicesupport.product_type",
                    ),
                ),
            ],
        ),
    ]
