# Generated by Django 4.1.4 on 2023-03-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0017_alter_alarm_comments_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="training_model",
            old_name="Manual_storage",
            new_name="Training_storage",
        ),
        migrations.AlterField(
            model_name="alarm_comments",
            name="support",
            field=models.IntegerField(),
        ),
    ]
