# Generated by Django 4.1.4 on 2023-03-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "servicesupport",
            "0018_rename_manual_storage_training_model_training_storage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="training_model",
            name="System_name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Training_system",
                to="servicesupport.system_types",
            ),
            preserve_default=False,
        ),
    ]
