# Generated by Django 4.1.4 on 2023-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "servicesupport",
            "0020_alarm_comments_updated_at_alarm_detail_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="training_model",
            name="Type",
            field=models.CharField(
                choices=[("Training", "Training"), ("Procedure", "Procedure")],
                default="1",
                max_length=20,
            ),
        ),
    ]
