# Generated by Django 4.1.4 on 2023-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0021_training_model_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training_model",
            name="Type",
            field=models.CharField(
                choices=[("Training", "Training"), ("Procedure", "Procedure")],
                default="Training",
                max_length=20,
            ),
        ),
    ]
