# Generated by Django 4.1.4 on 2023-03-24 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0022_alter_training_model_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="alarm_comments",
        ),
    ]
