# Generated by Django 4.1.4 on 2023-03-24 06:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0023_delete_alarm_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="std",
            name="Product_type",
        ),
        migrations.AddField(
            model_name="std",
            name="Part_used",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="std",
            name="file",
            field=models.FileField(default=None, upload_to="uploads/STD/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="std",
            name="MTB_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="std",
            name="Machine_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="std",
            name="problem_solved",
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="std",
            name="special_comments",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name="std_partused",
        ),
    ]
