# Generated by Django 4.1.4 on 2023-03-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "servicesupport",
            "0024_remove_std_product_type_std_part_used_std_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_type",
            name="product",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="specification",
            unique_together={("parentspec", "childspec")},
        ),
        migrations.AlterUniqueTogether(
            name="system_types",
            unique_together={("product_name", "system_names")},
        ),
    ]
