# Generated by Django 4.1.4 on 2023-03-24 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0025_alter_product_type_product_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="specification",
            unique_together=set(),
        ),
    ]
