# Generated by Django 4.1.4 on 2023-03-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0026_alter_specification_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specification",
            name="parentspec",
            field=models.CharField(max_length=55),
        ),
    ]
