# Generated by Django 4.1.4 on 2023-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0027_alter_specification_parentspec"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="RegisteredDate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="SpecialSpec",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="TerminatedDate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="hierarchy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="level",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="level_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="mainte_level",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="old",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="remarks",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="spare_type",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="spec_PartsName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="spec_parent",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="specification",
            name="stockrank",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="specification",
            name="childname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="specification",
            name="parentname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="specification",
            name="qty",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
