# Generated by Django 4.1.4 on 2023-04-19 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0028_specification_registereddate_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="userdetails",
        ),
    ]
