# Generated by Django 4.1.4 on 2023-04-19 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0029_delete_userdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="led",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_name", models.CharField(blank=True, max_length=100, null=True)),
                ("Manual_storage", models.FileField(upload_to="uploads/alarm_led/")),
                ("comments", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Product_led_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_system",
                        to="servicesupport.system_types",
                    ),
                ),
            ],
        ),
    ]
