# Generated by Django 4.1.4 on 2023-04-19 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0030_led"),
    ]

    operations = [
        migrations.DeleteModel(
            name="alarm_led",
        ),
    ]
