# Generated by Django 4.1.4 on 2023-04-19 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicesupport", "0031_delete_alarm_led"),
    ]

    operations = [
        migrations.RenameField(
            model_name="led",
            old_name="Product_led_name",
            new_name="Product_name",
        ),
        migrations.RenameField(
            model_name="led",
            old_name="Manual_storage",
            new_name="pdf_storage",
        ),
    ]
