# Generated by Django 4.2.1 on 2023-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesupport', '0033_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='ip',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
