# Generated by Django 4.2.1 on 2023-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesupport', '0034_analytics_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='spec_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_no', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='uploads/images/')),
                ('weight', models.IntegerField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
