# Generated by Django 4.2.1 on 2024-05-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicesupport', '0038_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec_details',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spec_details',
            name='consumable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spec_details',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spec_details',
            name='description_local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spec_details',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spec_details',
            name='exchangeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spec_details',
            name='hsn',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='spec_details',
            name='large_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicesupport.product_type'),
        ),
        migrations.AddField(
            model_name='spec_details',
            name='repairable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spec_details',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
