# Generated by Django 4.2.1 on 2024-05-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicesupport', '0039_spec_details_comments_spec_details_consumable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13)),
                ('code', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Storage_loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_location', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='spec_details',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_stock', models.CharField(blank=True, max_length=5, null=True)),
                ('special_stock_number', models.CharField(blank=True, max_length=30, null=True)),
                ('batch', models.CharField(blank=True, max_length=30, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('transit', models.IntegerField(blank=True, null=True)),
                ('returns', models.IntegerField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servicesupport.spec_details')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servicesupport.plant')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='servicesupport.storage_loc')),
            ],
        ),
    ]
