# Generated by Django 4.2.1 on 2024-05-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesupport', '0040_plant_storage_loc_alter_spec_details_weight_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec_details',
            name='hsn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
