# Generated by Django 4.2.1 on 2024-05-11 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicesupport', '0041_alter_spec_details_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
