# Generated by Django 4.2.1 on 2024-05-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesupport', '0042_stock_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='batch',
        ),
    ]
