# Generated by Django 6.0 on 2026-03-20 04:05

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesupport', '0043_remove_stock_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='STDReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('product', models.CharField(choices=[('CNC', 'CNC'), ('Servo', 'Servo'), ('Robot', 'Robot'), ('RM', 'RM'), ('Robocut', 'Robocut'), ('Robodrill', 'Robodrill'), ('Roboshot', 'Roboshot'), ('Laser', 'Laser'), ('Other', 'Other')], max_length=20)),
                ('content_type', models.CharField(choices=[('Content/Solution', 'Content/Solution'), ('Others', 'Others')], default='Content/Solution', max_length=30)),
                ('controller_model', models.CharField(blank=True, max_length=50, null=True)),
                ('controller_sl_no', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_model', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_sl_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rm_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Laser/RO/RM Model')),
                ('rm_sl_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Laser/RO/RM Sl. No.')),
                ('machine_tool_builder', models.CharField(blank=True, max_length=100, null=True)),
                ('configuration', models.CharField(blank=True, max_length=100, null=True)),
                ('end_user', models.CharField(blank=True, max_length=150, null=True)),
                ('application', models.CharField(blank=True, max_length=100, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('mr_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='MR No.')),
                ('mr_review', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multiple_visit', models.BooleanField(default=False)),
                ('visits_count', models.PositiveSmallIntegerField(default=1)),
                ('hours_count', models.PositiveSmallIntegerField(default=0)),
                ('repeat_visit_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('reason_for_subject', models.TextField(help_text='Why are you presenting this subject?', max_length=500)),
                ('problem_reported', models.TextField(max_length=500, verbose_name='Problem as reported by End-user')),
                ('problem_observation', models.TextField(max_length=1000, verbose_name='Observation of the problem with detailed description')),
                ('problem_suspected', models.TextField(max_length=500, verbose_name='Problem suspected by FSE/SRC')),
                ('problem_history', models.TextField(blank=True, max_length=500, null=True, verbose_name='History of the problem')),
                ('external_disturbance', models.TextField(blank=True, max_length=300, null=True, verbose_name='Was there any specific external disturbance?')),
                ('occurrence_count', models.TextField(blank=True, max_length=200, null=True, verbose_name='How many times has it occurred?')),
                ('diagnosis_info', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Diagnosis information as per manual')),
                ('analysis', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Describe step-by-step analysis. You can paste/insert images.', null=True, verbose_name='How was the problem analyzed?')),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='How was the Problem Solved?')),
                ('additional_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Any additional information')),
                ('parts_used_json', models.TextField(blank=True, help_text='Managed by form UI — do not edit manually', null=True, verbose_name='Parts replaced (JSON)')),
                ('applicable_models', models.TextField(blank=True, max_length=300, null=True)),
                ('useful_telephonic', models.BooleanField(blank=True, null=True, verbose_name='Content useful for Telephonic Support?')),
                ('supports_mttr', models.BooleanField(blank=True, null=True, verbose_name='Supports MTTR?')),
                ('special_tool', models.TextField(blank=True, max_length=300, null=True, verbose_name='Any Special Tool used for Troubleshooting')),
                ('alternate_process', models.TextField(blank=True, max_length=500, null=True, verbose_name='Any alternate process to troubleshoot')),
                ('reviewer_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_prepared', to=settings.AUTH_USER_MODEL)),
                ('presented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_presented', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_reviewed', to=settings.AUTH_USER_MODEL)),
                ('st_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_st_review', to=settings.AUTH_USER_MODEL)),
                ('system_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicesupport.system_types')),
            ],
            options={
                'verbose_name': 'STD Report',
                'verbose_name_plural': 'STD Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='STDApprovalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_log', to='servicesupport.stdreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
