"""
Django settings for fanuc_service project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-md*w9@uywja^wno6r^$x(#240$))4r@8*fr4ee)nwgx1zml0w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.4.105','127.0.0.1','192.168.43.76','localhost',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'servicesupport',
    'ckeditor',
     'ckeditor_uploader',
    'import_export',
    'rest_framework',
    #'django_auth_adfs',
    
]
DEFAULT_AUTO_FIELD='django.db.models.AutoField' 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django_auth_adfs.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'fanuc_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'servicesupport', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fanuc_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR),
)

SESSION_COOKIE_AGE = 3600 

# Allow larger POST body for .docx upload (default is 2.5MB — too small)
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024   # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE  = 50 * 1024 * 1024   # 50 MB

CKEDITOR_UPLOAD_PATH = "uploads/ckeditor/"
CKEDITOR_IMAGE_BACKEND = "pillow"   # pip install Pillow if not installed
CKEDITOR_CONFIGS = {
    'default': {
        # Use the full toolbar (all buttons)
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike',
             'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'],
            ['Source'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['NumberedList', 'BulletedList'],
            ['Indent', 'Outdent'],
            ['Maximize'],
        ],
 
        # Editor dimensions
        'width':  '100%',
        'height': 350,
 
        # Enable all extra plugins
        'extraPlugins': ','.join([
            'uploadimage',    # drag-drop + paste image upload
            'image2',         # better image widget with resize handles
            'autoembed',
            'embedsemantic',
            'autogrow',       # editor grows with content
            'tableresize',    # drag to resize table columns
            'tabletools',     # merge/split cells
            'pastefromword',  # paste from Word with cleanup
            'pastetools',
            'colorbutton',
            'font',
            'justify',
            'showblocks',
            'div',
        ]),
 
        # Image 2 plugin — allows resize by dragging handle
        'image2_alignClasses': ['image-align-left', 'image-align-center', 'image-align-right'],
        'image2_captionedClass': 'image-captioned',
 
        # Auto-grow: editor expands as user types
        'autoGrow_minHeight':  200,
        'autoGrow_maxHeight':  800,
        'autoGrow_bottomSpace': 50,
 
        # Allow all content (don't strip any HTML)
        'allowedContent': True,
 
        # Paste cleanup
        'forcePasteAsPlainText': False,
        'pasteFilter': None,
 
        # Table defaults
        'tabletools_scopedHeaders': True,
 
        # Remove the "Powered by CKEditor" footer
        'removePlugins': 'elementspath',
 
        # Use Django's CSRF token for uploads
        'filebrowserUploadUrl':      '/ckeditor/upload/',
        'filebrowserImageUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl':      '/ckeditor/browse/',
 
        # Content CSS (styles inside the editor iframe)
        'contentsCss': [
            'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600&display=swap',
            # Inline style block below handles the rest
        ],
 
        # Skin
        'skin': 'moono-lisa',
    },
 
    # Minimal config for simple fields (alarm_data, special_tips)
    'minimal': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink'],
            ['Source'],
        ],
        'width':  '100%',
        'height': 150,
        'allowedContent': True,
        'removePlugins': 'elementspath',
    },
}
## IN PRODUCTION Static & MEDIA ROOT
#STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR

# for Decorators @loginRequired 
LOGIN_URL = '/login'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# EMAIL
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER ="mayank180limbachiya@gmail.com"
EMAIL_HOST_PASSWORD ="vedvqokpdmtyjuyu"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 

#IMPORT EXPORT Restrictions
IMPORT_EXPORT_IMPORT_PERMISSION_CODE = "import"

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES':['rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Adjust page size as needed
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}
'''
# Client secret is not public information. Should store it as an environment variable.

client_id = 'e16db199-62b0-4350-aa15-076cf3719d4e'
client_secret = 'oXO8Q~xuGAyZAYUYSfhQ1AjNXGkB4bwdY~jvgaBt'

#Gl~8Q~DDIe7uXefKIJw_lgfPQuQmgjsvXLGSrdlD



tenant_id = '5f4b290f-39e7-4135-9b77-b5eac2f11f94'

AUTH_ADFS = {
    'AUDIENCE': client_id,
    'CLIENT_ID': client_id,
    'CLIENT_SECRET': client_secret,
    'CLAIM_MAPPING': {'first_name': 'given_name',
                      'last_name': 'family_name',
                      'email': 'upn'},
    'GROUPS_CLAIM': 'roles',
    'MIRROR_GROUPS': True,
    'USERNAME_CLAIM': 'upn',
    'TENANT_ID': tenant_id,
    'RELYING_PARTY_ID': client_id,
}

AUTHENTICATION_BACKENDS = [
    'django_auth_adfs.backend.AdfsAccessTokenBackend',
]


# Configure django to redirect users to the right URL for login
LOGIN_URL = "django_auth_adfs:login"
LOGIN_REDIRECT_URL = "/"
'''